---
title: "Nonprofit Landscape: Initial Explorations"
format: 
    html:
        code-fold: true
---

A line of text describing initial setup and context for this work.

```{r setup}
#| include: false
library(tidyverse)
library(ggplot2)
library(usmap)
data <- read.csv("Data/Nonprofits2024.csv")
```

Some text describing overall nonprofit patterns in 2024.

```{r}
plot_usmap(
  data = data,
  values = "Count",
  color = "white",
  linewidth = 0.2
) +
  scale_fill_gradient(
    breaks = c(0, 50000, 100000, 150000),
    high = '#0072B2',
    low = 'white'
  ) +
  theme(legend.position = "top") +
  labs(fill = "Nonprofits") +
  guides(
    fill = guide_colorbar(
      barwidth = unit(5, 'cm')
    )
  )
```

Some text describing nonprofit density.

```{r}
## Map nonprofit density per state
plot_usmap(
  data = data,
  value = "NPDensity",
  color = "white",
  linewidth = 0.2
) +
  scale_fill_gradient(
    breaks = c(0, 5, 10, 15),
    high = '#0072B2',
    low = 'white'
  ) +
  theme(legend.position = "top") +
  labs(fill = "Nonprofits per 1,000 people")
```

Some text describing nonprofit asset density.

```{r}
## Map nonprofit asset density per state
plot_usmap(
  data = data,
  value = "AssetDensity",
  color = "white",
  linewidth = 0.2
) +
  scale_fill_gradient(
    breaks = c(25000, 50000, 75000),
    high = '#0072B2',
    low = 'white'
  ) +
  theme(legend.position = "top") +
  labs(fill = "Nonprofit Assets per person") +
  guides(
    fill = guide_colorbar(
      barwidth = unit(5, 'cm')
    )
  )
```

Next steps: Further cleaning of the dataset, identifying other relevant metrics, and refining maps.